Week 2 tasks
Teaching-projects/SZE-MOSZE-2020-Gateway pull request #2
Opened 2020-09-24 13:15 UTC by hmartin28

2020-09-24 16:30 UTC, hegyhati commented
Ti most egyesevel toltogettetek fel a fajlokat? Minek? Illetve conflictoltok a masterrel, tessek rebase-elni ra, mert ezt meg az initrol inditottatok.

2020-09-24 18:57 UTC, hmartin28 commented
@hegyhati Ha kitörölném az init és a dev2 branchet és utána nyitnék egy újat a masterből és arra megcsinálnám a feladatot és arra kérnék utána egy PR-t úgy is jó lenne?

2020-09-24 22:23 UTC, hegyhati commented
Most hova dolgozol? Ahogy irtam, ne mashol dolgozzatok es copyzzatok a kodot. A git pont az ilyen hulyesegek ertelmes kezelesere (is) jo. Csak meg kell tanulni hasznalni.

2020-09-25 05:44 UTC, hmartin28 commented
@oliverosz Elvileg javítottam, nincs init branch és a conflict is megszűnt

2020-09-25 19:37 UTC, oliverosz requested changes
>Monsters, monsters everywhere!

A `units` könyvtárban lévők maradjanak, a gyökérben lévők nem kellenek.

A README-t is frissítsétek.

2020-09-25 19:37 UTC, oliverosz commented on monster.hpp
> +#include <fstream>
Az fstream nincs használva a headerben, feleslegesen ne legyen include-olva.

2020-09-25 19:37 UTC, oliverosz commented on monster.hpp
> +  int dmg;
Miért tűntek el a `const`ok? Továbbra sem módosíthatók ezek az adattagok a létrehozás után. A parsolásnál a megfelelő értékekkel kell létrehozni a példányokat, nem utólag módosítani azok értékeit.

2020-09-25 19:37 UTC, oliverosz commented on monster.hpp
> +  Monster() {}
Ne legyen default konstruktor, akkor helytelenül lesz inicializálva az objektum. Létrehozáskor mindig meg kelljen adni a statjait.

2020-09-25 19:37 UTC, oliverosz commented on monster.cpp
> +    Monster monster(name,hp,dmg);
Úgy látom, nem is a default konstruktor van használva, akkor nem is értem, miért kellett módosítani azon meg a const adattagokon.

2020-09-25 19:37 UTC, oliverosz commented on monster.cpp
> +    name = line.substr(posColon+3,(posComma-1)-(posColon+3));
Ennyire azért ne legyen érzékeny a whitespace-ekre. A kettőspont és a vessző körül tetszőleges számú szóköz és tabulátor lehet. (A valóságban sortörés is, de azt az esetet most még nem muszáj tudni kezelni.)
És annyit azért ellenőrizzen le, hogy tényleg az a kulcs, hogy `"name"`.

2020-09-25 19:37 UTC, oliverosz commented on monster.cpp
> +    std::cerr << "Hiba a fajl megnyitasakor!";
>Az egyetlen hiba, amire fel kell kesziteni a dolgot, hogy maga a fajl nem letezik, ekkor dobjon valami exceptiont, amit a main-ben kezeljunk is le.

Tehát exceptionnel legyen megoldva a hiba kezelése.

2020-09-25 19:37 UTC, oliverosz commented on main.cpp
> +  Monster monster2 = Monster::readJson(argv[2]);
Ahogy az előző változatban, most is legyen ellenőrizve az argumentumok száma.

2020-09-27 19:10 UTC, hmartin28 commented
@oliverosz Javítottam

2020-09-28 15:37 UTC, oliverosz commented on monster.cpp
> +    name = line.substr(posColon+3,(posComma-1)-(posColon+3));
@hmartin28 Ez a rész nem lett javítva. De mivel a json parsert úgyis tovább kell fejleszteni, egyelőre elfogadom így.

2020-09-28 15:39 UTC, oliverosz approved these changes
EDIT: Ez a komment már nem érvényes.
Amik ehhez a PR-hoz tartoznak, azok rendben vannak, de találtam hibát az első feladat megoldásában, annak nyitni fogok egy issue-t. Javítsátok ki egy külön branchen, és nyissatok neki egy új PR-t.

2020-09-28 15:47 UTC, oliverosz requested changes
Cancel. Most látom, hogy a gyökérkönyvtárban lévő unitok nem lettek törölve, amit kértem.

Az előző reviewban említett hiba sem annyira súlyos, mint elsőre gondoltam: Csak ki kell törölni a `Monster::hpDown` metódust. Először azt hittem, az hívódik kívülről, de már látom, hogy van `monsterAttack` metódus is. Elég ha az csökkenti a célpont életét. Viszont ez legyen const metódus, hiszen a támadó nem módosulhat a támadás során. (És ha a paraméter `target`nek lenne nevezve, akkor könnyebben érthető lenne, mit akar ez a metódus.)

2020-09-29 07:22 UTC, hegyhati commented
Sracok, akkor ezt a par dolgot meg javitsatok ki pls, aztan utana beviszem.

2020-09-29 13:40 UTC, hmartin28 commented
@oliverosz Kitöröltem a kettő jsont a gyökérkönyvtárból, átalakítottam a monsterAttack függvényt és kitöröltem a hpDown-t

2020-09-30 09:19 UTC, oliverosz approved these changes
@hmartin28 A hpDown függvényt nem kitörölted, hanem kikommentelted. A kommentek a kód dokumentálására vannak. A régi, már nem használt kódok visszanézhetők git historyból, ez az egyik funkciója a verziókezelésnek, nem kell ezeket meghagyni kikommentelve.

@hegyhati Egyébként most már rendben van, mehet a merge.

2020-09-30 10:12 UTC, merged