levelup
Teaching-projects/SZE-MOSZE-2020-Gateway pull request #4
Opened 2020-10-14 16:24 UTC by hmartin28

2020-10-14 16:25 UTC, hmartin28 commented
@oliverosz Azt szeretném kérdezni, hogy elég azt a callgrindot el artifactolni amit megcsináltam, vagy azt a callgrind_annotate callgrind.out..... fájlt kéne valahogy artifactolni?

2020-10-15 14:05 UTC, oliverosz requested changes
> @oliverosz Azt szeretném kérdezni, hogy elég azt a callgrindot el artifactolni amit megcsináltam, vagy azt a callgrind_annotate callgrind.out..... fájlt kéne valahogy artifactolni?

@hmartin28 Callgrind használata nem volt a feladatban. Azt CI-ban automatizálni nem is nagyon lehet, csak manuális analízishez használható. A cppcheck által jelzett style és performance üzeneteket kellene artifactolni. (Az a rész jó, hogy az error/warning esetén hibával leállítja a workflowt, a style hibáknál ez nem kell, csak az artifact.)

A többit kommentben jeleztem.

2020-10-15 14:05 UTC, oliverosz commented on main.cpp
> +  if (monster1.isDefeated() == true) {
`if (monster1.isDefeated())`

2020-10-15 14:05 UTC, oliverosz commented on monster.cpp
> +float Monster::getLvl() { return lvl; }
Ezek a getterek is legyenek constok, a `getName` meg const referenciát adjon vissza.

2020-10-15 14:05 UTC, oliverosz commented on monster.cpp
> +    xp += dmg;
Jó lenne, ha a HP nem menne mínuszba. És ha a sebzés nagyobb, mint a HP, akkor csak annyi XP-t kapjon, amennyi sebzést ténylegesen okozott.

2020-10-15 14:05 UTC, oliverosz commented on monster.cpp
> +    }
Egy ütésből tudjon több szintet is lépni egyszerre.

2020-10-15 14:05 UTC, oliverosz commented on .github/workflows/First_Flow.yml
> +      - run: g++ *.cpp -o a.out -Wall -Wextra -g
Legyen még ott egy `-Werror` is.

2020-10-15 14:05 UTC, oliverosz commented on .github/workflows/First_Flow.yml
> +      - run: valgrind --track-origins=yes --leak-check=full --log-file=leaklogfile.txt --error-exitcode=-1 ./a.out units/monster1.json units/monster2.json
Én negatív exitcode-nál úgy tapasztaltam, hogy nem működik rendesen, inkább pozitív számot adj meg neki.

2020-10-16 18:56 UTC, hmartin28 commented
@oliverosz Javítottam

2020-10-17 09:05 UTC, oliverosz requested changes
Alakul, már csak ezt a pár apróságot kell javítani.

2020-10-17 09:05 UTC, oliverosz commented on monster.hpp
> +  float pot_Xp = 0;
Ez nem az objektum állapotához tartozó adat (minden állapotban 0). Ez egy segédváltozó, ami egy metódushoz van használva, akkor legyen ott egy lokális változó, ne egy tagváltozó.

2020-10-17 09:05 UTC, oliverosz commented on monster.cpp
> +      hp = floor(hp*pow(1.1,mp));
Kerekíteni kellett, nem az egész részét venni. És inkább mxhp-nak kéne nevezni, mert így könnyen összetéveszthető az akthp-val.

2020-10-17 09:05 UTC, oliverosz commented on monster.cpp
> +  if (getaktHp() > 0) {
Ahelyett, hogy az egész függvény egy `if` blokkban van, inkább az elején legyen egy `if (akthp <= 0) return;`

2020-10-17 10:08 UTC, hmartin28 commented
@oliverosz Elvileg javítva

2020-10-17 10:31 UTC, oliverosz approved these changes

2020-10-17 10:32 UTC, oliverosz commented
Úgy látom, ehhez a repóhoz még nincs write accessem. @hegyhati

2020-10-17 13:58 UTC, hegyhati commented
@oliverosz adtam.

2020-10-17 14:02 UTC, merged